# Generated by Django 4.0.1 on 2026-03-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FalseDemandRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('location_code', models.CharField(max_length=100)),
                ('requested_amount', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='docs/')),
                ('circle_id', models.CharField(max_length=100)),
                ('division_id', models.CharField(max_length=100)),
            ],
        ),
    ]
