# Generated by Django 5.1.4 on 2026-03-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('false_demand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_name', models.CharField(max_length=255)),
                ('division_name', models.CharField(max_length=255)),
                ('zone_name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('division_id', models.CharField(blank=True, max_length=50, null=True)),
                ('short_code', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('circle_id', models.CharField(blank=True, max_length=50, null=True)),
                ('region_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
