# Generated by Django 5.1.4 on 2026-03-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('false_demand', '0002_locationdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdetails',
            name='circle_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='division_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
