# Generated by Django 5.1.4 on 2026-03-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('false_demand', '0003_alter_locationdetails_circle_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='falsedemandrequest',
            name='request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
