# Generated by Django 5.1.4 on 2026-03-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('false_demand', '0004_falsedemandrequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falsedemandrequest',
            name='request_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
