# Generated by Django 5.1.4 on 2026-03-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('false_demand', '0005_alter_falsedemandrequest_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='falsedemandrequest',
            name='consumer_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
