# Generated by Django 5.1.4 on 2026-03-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('false_demand', '0006_falsedemandrequest_consumer_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='falsedemandrequest',
            name='ao_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='ao_doc',
            field=models.FileField(blank=True, null=True, upload_to='ao_docs/'),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='ao_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='ao_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='cgm_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='cgm_doc',
            field=models.FileField(blank=True, null=True, upload_to='cgm_docs/'),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='cgm_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='cgm_status',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='dgm_onm_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='dgm_onm_doc',
            field=models.FileField(blank=True, null=True, upload_to='dgm_onm_docs/'),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='dgm_onm_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='dgm_onm_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='dgm_vig_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='dgm_vig_doc',
            field=models.FileField(blank=True, null=True, upload_to='dgm_vig_docs/'),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='dgm_vig_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='dgm_vig_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='gm_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='gm_doc',
            field=models.FileField(blank=True, null=True, upload_to='gm_docs/'),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='gm_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='gm_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='zonal_officer_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='zonal_officer_doc',
            field=models.FileField(blank=True, null=True, upload_to='zo_docs/'),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='zonal_officer_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='zonal_officer_status',
            field=models.IntegerField(default=0),
        ),
    ]
