# Generated by Django 5.1.4 on 2026-03-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('false_demand', '0007_falsedemandrequest_ao_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='falsedemandrequest',
            name='ao_name_mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='cgm_name_mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='dgm_onm_name_mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='dgm_vig_name_mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='gm_name_mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='falsedemandrequest',
            name='zonal_officer_name_mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
