# Generated by Django 5.1.4 on 2026-03-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('false_demand', '0008_falsedemandrequest_ao_name_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='falsedemandrequest',
            name='terrif_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='falsedemandrequest',
            name='cgm_status',
            field=models.IntegerField(default=0),
        ),
    ]
