# Generated by Django 5.1.4 on 2026-03-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('false_demand', '0009_falsedemandrequest_terrif_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falsedemandrequest',
            name='requested_amount',
            field=models.BigIntegerField(max_length=50),
        ),
    ]
