# Generated by Django 5.1.4 on 2026-03-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('false_demand', '0010_alter_falsedemandrequest_requested_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falsedemandrequest',
            name='requested_amount',
            field=models.BigIntegerField(),
        ),
    ]
