# Generated by Django 5.1.4 on 2026-03-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('false_demand', '0011_alter_falsedemandrequest_requested_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='falsedemandrequest',
            name='final_puss_status',
            field=models.IntegerField(default=0),
        ),
    ]
